services:
  - type: web
    name: bakery-mgt-system
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: bakery-db
          property: connectionString
