"""Initial migration

Revision ID: e820151d2877
Revises: 
Create Date: 2025-08-10 19:24:10.673554

"""
from werkzeug.security import generate_password_hash
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Boolean
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e820151d2877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidhaa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b_name', sa.String(length=100), nullable=False),
    sa.Column('b_bei', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('b_name')
    )
    op.create_table('mapato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiasi', sa.Float(), nullable=False),
    sa.Column('aina', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matumizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiasi', sa.Float(), nullable=False),
    sa.Column('aina', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madeni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kiasi_kalipa', sa.Integer(), nullable=False),
    sa.Column('kiasi_baki', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_madeni_bid_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('position_as', sa.String(length=150), nullable=True),
    sa.Column('phone_no', sa.String(length=20), server_default='0000000000', nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name='fk_user_shift_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('uzalishaji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('b_jumla', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_uzalishaji_bid_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manunuzi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('maligafi', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('idadi', sa.Integer(), nullable=False),
    sa.Column('bei', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_manunuzi_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mauzo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('b_uza', sa.Integer(), nullable=True),
    sa.Column('b_bei_uza', sa.Integer(), nullable=True),
    sa.Column('jumla', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_mauzo_bid_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_mauzo_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid_id')
    )
    op.create_table('mpishi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pondo', sa.Integer(), nullable=False),
    sa.Column('idadi', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_mpishi_bid_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_mpishi_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maligafi', sa.String(length=50), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('idadi', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_store_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # Insert initial admin user
     # Insert hardcoded admin user
    user_table = table('user',
        column('id', Integer),
        column('name', String),
        column('email', String),
        column('is_active', Boolean),
        column('position_as', String),
        column('phone_no', String),
        column('password', String),
        column('shift_id', Integer)
    )

    op.bulk_insert(user_table,
        [
            {
                'id': 1,
                'name': 'Admin',
                'email': 'anicetysanya@gmail.com',
                'is_active': True,
                'position_as': '',
                'phone_no': '0000000000',
                'password': generate_password_hash('sani'),
                'shift_id': None
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('mpishi')
    op.drop_table('mauzo')
    op.drop_table('manunuzi_data')
    op.drop_table('uzalishaji')
    op.drop_table('user')
    op.drop_table('madeni')
    op.drop_table('shift')
    op.drop_table('matumizi')
    op.drop_table('mapato')
    op.drop_table('bidhaa')
    # ### end Alembic commands ###
