"""Initial migration

Revision ID: f7c08df51483
Revises: 
Create Date: 2025-08-10 20:00:25.877890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c08df51483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidhaa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b_name', sa.String(length=100), nullable=False),
    sa.Column('b_bei', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('b_name')
    )
    op.create_table('mapato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiasi', sa.Float(), nullable=False),
    sa.Column('aina', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matumizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiasi', sa.Float(), nullable=False),
    sa.Column('aina', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madeni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kiasi_kalipa', sa.Integer(), nullable=False),
    sa.Column('kiasi_baki', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_madeni_bid_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('position_as', sa.String(length=150), nullable=True),
    sa.Column('phone_no', sa.String(length=20), server_default='0000000000', nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name='fk_user_shift_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('uzalishaji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('b_jumla', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_uzalishaji_bid_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manunuzi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('maligafi', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('idadi', sa.Integer(), nullable=False),
    sa.Column('bei', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_manunuzi_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mauzo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('b_uza', sa.Integer(), nullable=True),
    sa.Column('b_bei_uza', sa.Integer(), nullable=True),
    sa.Column('jumla', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_mauzo_bid_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_mauzo_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid_id')
    )
    op.create_table('mpishi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pondo', sa.Integer(), nullable=False),
    sa.Column('idadi', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bidhaa.id'], name='fk_mpishi_bid_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_mpishi_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maligafi', sa.String(length=50), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('idadi', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_store_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('mpishi')
    op.drop_table('mauzo')
    op.drop_table('manunuzi_data')
    op.drop_table('uzalishaji')
    op.drop_table('users')
    op.drop_table('madeni')
    op.drop_table('shift')
    op.drop_table('matumizi')
    op.drop_table('mapato')
    op.drop_table('bidhaa')
    # ### end Alembic commands ###
